// generated by Bing AI using the following prompts:
// complete this code snippet using info about intel chen of upenn const quizzes = [ { id: 1, name: "All About Intel", description: "See how much you know about Intel", questions: []} ];
// add another quiz in that snippet about web3builders, a club at upenn

const quizzes = [
    { id: 1, name: "All About Intel", description: "See how much you know about Intel", questions: [
        { id: 1, text: "What is Intel's full name?", choices: ["Yiheng Chen", "Yiheng 'Intel' Chen", "Intel Yiheng Chen", "Chen Yiheng"], answer: 1},
        { id: 2, text: "What program is Intel enrolled in at UPenn?", choices: ["Management & Technology", "Computer Science & Engineering", "Data Science & Business Analytics", "Robotics & Photography"], answer: 0},
        { id: 3, text: "What is the name of Intel's chrome extension project?", choices: ["Panopto Lecture Downloader", "Chess.com Adoption Analysis", "Covid-Vac-Tracker", "Penn Web3 Builders"], answer: 0},
        { id: 4, text: "What company did Intel co-found?", choices: ["Galaxy", "Slack", "Netflix", "Amazon"], answer: 0}
    ]},
    { id: 2, name: "All About Web3 Builders", description: "See how much you know about Web3 Builders", questions:[
        { id :1 , text:"What is the mission of Web3 Builders?", choices:["To empower students and expose them to engineering opportunities in blockchain and web3 development.", 
        "To create a vibrant community of web3 builders and engineers at UPenn.", 
        "To host weekly workshops, events and social gatherings on web3 technologies.", 
        "All of the above."], answer :3 },
        { id :2 , text:"Who is one of the co-founders of Web3 Builders?", choices:["Brandon Kong",
        	"Lisa Chen",
        	"Jason Wilson",
        	"Cheng Ji"], answer :0 },
        { id :3 , text:"Which event did Web3 Builders host on National Frozen Yogurt Day?", choices:["Intro to Blockchain Technology Seminar",
        	"Intro to Blockchain Technology Seminar - Advanced Topics",
        	"Investing in Web 3.0 with Binance Labs & The Brooker Group",
        	"2022 Penn Wharton China Summit - Envisage the Future Panel"], answer :1 },
        { id :4 , text:"Which website can you visit to learn more about Web3 Builders?", choices:["https://www.web3builders.community/",
        	"https://pennclubs.com/club/crypto-builders",
        	"https://www.linkedin.com/company/penn-web3-builders",
        	"All of the above."], answer :4 }
    ]}
]

export default quizzes